[package]
edition = "2021"
name = "baml-schema-build"
version.workspace = true
authors.workspace = true
description.workspace = true
license-file.workspace = true

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "=0.2.92"
js-sys = "=0.3.69"
wasm-bindgen-futures = "0.4.42"
wasm-logger = { version = "0.2.0" }
baml-fmt = { path = "../baml-fmt" }
baml-runtime = { path = "../baml-runtime", features = [
  "wasm",
  "internal",
], default-features = false }
anyhow = { version = "1" }
serde = { version = "1.0", features = ["derive"] }
serde-wasm-bindgen = "0.4"

[dependencies.web-sys]
version = "0.3.69"
features = [
  'Headers',
  'Request',
  'RequestInit',
  'RequestMode',
  'Response',
  'Window',
]
