[package]
edition = "2021"
name = "baml-schema-build"
version.workspace = true
authors.workspace = true
description.workspace = true
license-file.workspace = true

[lib]
crate-type = ["cdylib"]

[dependencies]
anyhow.workspace = true
baml-fmt = { path = "../baml-fmt" }
baml-runtime = { path = "../baml-runtime", features = [
  "wasm",
  "internal",
], default-features = false }
console_log = { version = "1", features = ["color"] }
js-sys = "=0.3.69"
log.workspace = true
serde.workspace = true
serde_json.workspace = true
serde-wasm-bindgen = "0.4"
wasm-bindgen = "=0.2.92"
wasm-bindgen-futures = "0.4.42"
wasm-logger = { version = "0.2.0" }
indexmap.workspace = true

[dependencies.web-sys]
version = "0.3.69"
features = [
  'console',
  'Headers',
  'Request',
  'RequestInit',
  'RequestMode',
  'Response',
  'Window',
]
