[workspace]
resolver = "2"
members = [
  "baml-lib/*",
  "baml-cli",
  "baml-fmt",
  "baml-schema-wasm",
  "baml-core-ffi",
  "client-llm",
  "toy-cli",
]

[workspace.dependencies]
internal-baml-client-llm = { path = "client-llm" }

anyhow = "1.0"
env_logger = "0.11.3"
log = "0.4.20"
indexmap = { version = "2.1.0", features = ["serde"] }
indoc = "2.0.1"
reqwest = { version = "0.11.22", features = ["native-tls-vendored"] }
serde_json = { version = "1", features = ["float_roundtrip", "preserve_order"] }
serde = { version = "1", features = ["derive"] }

[workspace.package]
version = "0.18.0-canary.4"
authors = ["Boundary <contact@boundaryml.com>"]

description = "BAML Toolchain"
license-file = "LICENSE"

[workspace.metadata.workspaces]
allow_branch = "canary"

[profile.release]
lto = true
