[package]
edition = "2021"
name = "baml-runtime"
version.workspace = true
authors.workspace = true
description.workspace = true

license-file.workspace = true

[dependencies]
anyhow.workspace = true
jsonish = { path = "../baml-lib/jsonish" }
internal-baml-core = { path = "../baml-lib/baml-core" }
internal-baml-jinja = { path = "../baml-lib/jinja" }
clap = { version = "4.4.6", features = ["cargo", "derive"] }
env_logger.workspace = true
internal-baml-client-llm = { path = "../baml-lib/client-llm" }
log.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
uuid = { version = "1.7.0", features = ["v4"] }
json_comments = "0.2.2"
dunce = "1.0.4"
strsim = "0.11.1"
either = "1.8.1"
futures = "0.3.30"
async-stream = "0.3.5"
async-trait = "0.1.80"
walkdir.workspace = true
colored = "2.1.0"
indexmap.workspace = true

[dev-dependencies]
base64 = "0.13.0"
dissimilar = "1.0.4"
expect-test = "1.1.0"
indoc.workspace = true
either = "1.8.1"
