[package]
edition = "2021"
name = "baml-runtime"
version.workspace = true
authors.workspace = true
description.workspace = true

license-file.workspace = true

[dependencies]
anyhow.workspace = true
jsonish = { path = "../baml-lib/jsonish" }
internal-baml-core = { path = "../baml-lib/baml-core" }
internal-baml-jinja = { path = "../baml-lib/jinja" }
# internal-baml-client-llm = { path = "../baml-lib/client-llm" }
log.workspace = true
serde.workspace = true
serde_json.workspace = true
uuid = { version = "1.7.0", features = ["v4"] }
json_comments = "0.2.2"
dunce = "1.0.4"
strsim = "0.11.1"
either = "1.8.1"
walkdir.workspace = true
colored = "2.1.0"
indexmap.workspace = true
tokio = { version = "1", default-features = false, features = [
  "macros",
  "time",
] }


[dependencies.wasm-bindgen]
version = "^0.2.74"
optional = true
features = ["serde-serialize"]

[dependencies.js-sys]
version = "0.3.69"
optional = true

[dependencies.web-sys]
version = "0.3.69"
optional = true
features = ["Headers", "Request", "RequestInit", "RequestMode"]

[features]
default = []
wasm = [
  "wasm-bindgen",
  "js-sys",
  "web-sys",
  "colored/no-color",
  "uuid/js",
] # Enable this feature for WASM build
network = ["tokio/full"]

[dev-dependencies]
base64 = "0.13.0"
dissimilar = "1.0.4"
expect-test = "1.1.0"
indoc.workspace = true
either = "1.8.1"
