[package]
edition = "2021"
name = "client-llm"
version.workspace = true
authors.workspace = true
description.workspace = true
license-file.workspace = true

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "=0.2.92"
wasm-logger = { version = "0.2.0" }
