[package]
edition = "2021"
name = "internal-baml-parser-database"
version.workspace = true
authors.workspace = true
description.workspace = true
licence = "Apache-2.0"
licence-file.workspace = true

[dependencies]
internal-baml-diagnostics = { path = "../diagnostics", version = "^0.0.1" }
internal-baml-schema-ast = { path = "../schema-ast", version = "^0.0.1" }

either = "1.6.1"
enumflags2 = "0.7"
indexmap = "1.8.0"
rustc-hash = "1.1.0"
colored = "2.0.0"
log = "0.4.20"
