[package]
edition = "2021"
name = "baml"
version.workspace = true
authors.workspace = true
description.workspace = true
licence = "Apache-2.0"
licence-file.workspace = true

[dependencies]
internal-baml-core = { path = "../baml-core", version = "^0.0.1" }


[dev-dependencies]
base64 = "0.13.0"
dissimilar = "1.0.4"
expect-test = "1.1.0"
indoc.workspace = true
either = "1.8.1"
