name: Canary Version Bumper

on:
  schedule:
    - cron: '0 0 * * *'  # every day

  workflow_dispatch:
    inputs:
      TYPE:
        description: 'Bump Type (prerelease, patch, minor, major)'
        required: true
        default: 'prerelease'
      CLI:
        description: 'Bump Rust CLI'
        required: true
        default: 'AUTO'
      CLIENT_PYTHON:
        description: 'Bump Python Client'
        required: true
        default: 'AUTO'
      VSCODE_EXT:
        description: 'Bump VSCode Extension'
        required: true
        default: 'AUTO'

jobs:
  bump_version:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: canary

    - name: Get last nightly commit hash on main
      id: last_commit
      run: |
        COMMIT_HASH=$(git log --oneline main | grep -E "\[NIGHTLY\]" | head -n 1 | awk '{print $1}')
        if [ -z "$COMMIT_HASH" ]; then
          COMMIT_HASH=$(git rev-list --max-parents=0 HEAD)
        fi
        echo ::set-output name=hash::${COMMIT_HASH}

    - name: Check for changes in specified folders since last autorelease
      id: diff_check
      run: |
        if [ "${{ github.event.inputs.VSCODE_EXT }}" == "AUTO" ]; then
          git diff --quiet ${{ steps.last_commit.outputs.hash }} HEAD -- ./vscode-ext && echo ::set-output name=vscode_ext_changed::0 || echo ::set-output name=vscode_ext_changed::1
        else
          echo ::set-output name=vscode_ext_changed::${{ github.event.inputs.VSCODE_EXT }}
        fi
        if [ "${{ github.event.inputs.CLI }}" == "AUTO" ]; then
          git diff --quiet ${{ steps.last_commit.outputs.hash }} HEAD -- ./cli && echo ::set-output name=cli_changed::0 || echo ::set-output name=cli_changed::1
        else
          echo ::set-output name=cli_changed::${{ github.event.inputs.CLI }}
        fi
        if [ "${{ github.event.inputs.CLIENT_PYTHON }}" == "AUTO" ]; then
          git diff --quiet ${{ steps.last_commit.outputs.hash }} HEAD -- ./client/python && echo ::set-output name=client_python_changed::0 || echo ::set-output name=client_python_changed::1
        else
          echo ::set-output name=client_python_changed::${{ github.event.inputs.CLIENT_PYTHON }}
        fi
        git diff --quiet ${{ steps.last_commit.outputs.hash }} HEAD -- ./docs && echo ::set-output name=docs_changed::0 || echo ::set-output name=docs_changed::1


    - name: Bump version - vscode-ext
      if: steps.diff_check.outputs.vscode_ext_changed == '1'
      run: |
        bumpversion --allow-dirty ${{ github.event.inputs.TYPE }}
      working-directory: ./vscode-ext

    - name: Bump version - cli
      if: steps.diff_check.outputs.cli_changed == '1'
      run: |
        bumpversion --allow-dirty ${{ github.event.inputs.TYPE }}
      working-directory: ./cli

    - name: Bump version - client-python
      if: steps.diff_check.outputs.client_python_changed == '1'
      run: |
        bumpversion --allow-dirty ${{ github.event.inputs.TYPE }}
      working-directory: ./clients/python
    
    - name: Create new commit
      if: steps.diff_check.outputs.vscode_ext_changed == '1' || steps.diff_check.outputs.cli_changed == '1' || steps.diff_check.outputs.client_python_changed == '1'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        COMMIT_MSG=""
        if [ "${{ steps.diff_check.outputs.cli_changed }}" == "1" ]; then
          COMMIT_MSG+="[NIGHTLY:cli] "
        fi
        if [ "${{ steps.diff_check.outputs.vscode_ext_changed }}" == "1" ]; then
          COMMIT_MSG+="[NIGHTLY:vscode_ext] "
        fi
        if [ "${{ steps.diff_check.outputs.client_python_changed }}" == "1" ]; then
          COMMIT_MSG+="[NIGHTLY:client-python] "
        fi
        echo git commit -am "${COMMIT_MSG}[AUTO] Version bump for nightly release"
    
    # - name: Push changes
    #   run: |
    #       git push
