name: Canary Nightly Release

on:
  push:
    branches:
      - canary

jobs:
  create_release:
    runs-on: ubuntu-latest

    # This string matches nightly_version.yml
    if: contains(github.event.head_commit.message, '[AUTO] Version bump for nightly release')

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Get Changes
        id: get_changes
        run: |
          COMMIT_MSG="${{ github.event.head_commit.message }}"
          echo "::set-output name=cli_changed::$(if [[ $COMMIT_MSG == *"[NIGHTLY:cli]"* ]]; then echo 1; else echo 0; fi)"
          echo "::set-output name=vscode_ext_changed::$(if [[ $COMMIT_MSG == *"[NIGHTLY:vscode_ext]"* ]]; then echo 1; else echo 0; fi)"
          echo "::set-output name=client_python_changed::$(if [[ $COMMIT_MSG == *"[NIGHTLY:client-python]"* ]]; then echo 1; else echo 0; fi)"

      - run: |
          pwd
          ls .github
      
      - name: VSCode Extension
        if: steps.get_changes.outputs.vscode_ext_changed == '1'
        uses: ./.github/actions/vscode
