name: Release engine/language_client_ruby

on:
  push:
    branches:
      - sam/rust-llm

permissions:
  contents: read
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: rubygems/configure-rubygems-credentials@main
        with:
          # https://rubygems.org/profile/oidc/api_key_roles/rg_oidc_akr_p6x4xz53qtk948na3bgy
          role-to-assume: rg_oidc_akr_p6x4xz53qtk948na3bg

      - uses: actions/checkout@v4

      - uses: oxidize-rb/actions/setup-ruby-and-rust@main
        with:
          rubygems: latest
          ruby-version: "3.2"
          bundler-cache: false
          cargo-cache: true
          cargo-vendor: true

      - uses: oxidize-rb/cross-gem-action@main
        with:
          platform: ${{ matrix.platform }}
          version: "latest"
          env: |
            RUBY_CC_VERSION=3.3.0:3.2.0:3.1.0:3.0.0

      - run: |
          for i in $(ls pkg/*.gem); do
            gem push $i
          done
