name: sandbox

on:
  workflow_dispatch: {}
  push:
    branches:
      - sam/mise-arm64

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  actions: read

jobs:
  gem_publish:
    runs-on: ubuntu-latest
    permissions:
      actions: read
    steps:


      - uses: actions/checkout@v4

      - uses: rubygems/configure-rubygems-credentials@main
        with:
          # https://rubygems.org/profile/oidc/api_key_roles/rg_oidc_akr_p6x4xz53qtk948na3bgy
          role-to-assume: rg_oidc_akr_p6x4xz53qtk948na3bgy

      - uses: jdx/mise-action@v2

      - uses: actions/download-artifact@v4
        with:
          pattern: gem-*
          run-id: 10068132399

      - working-directory: engine/language_client_ruby
        run: |
          for i in $(ls pkg/*.gem); do
            gem push $i
          done
  mise-in-aarch64:
    runs-on: ubuntu-latest
    container: ghcr.io/rust-cross/manylinux_2_28-cross:aarch64
    steps:
      - uses: actions/checkout@v4
      # - uses: actions/setup-python@v5
      #   with:
      #     python-version: "3.8"
      #     architecture: ${{ matrix._.host == 'windows-latest' && 'x64' || null }}
      - run: apt install libreadline-dev
      - uses: jdx/mise-action@v2
        env:
          MISE_DEBUG: 1
        with:
          version: 2024.7.4
          mise_toml: |
            [tools]
            ruby = "3.1.6"